### ISSUE TITLE
SkyX doesn't work often

### ISSUE THREAD

**Issue by shantanubdas2002** [geofs-plugins/plugin-manager#2] opened 2017-06-20 13:39 UTC
Although SkyX is claimed to be back and working now, it still doesnt work for me and some others. I installed SkyX from the Chrome Web Store and tampermonkey. Despite the amount of times I refresh the game and the extension from both tampermonkey and chrome web store it doesnt seem to work. SkyX only works very rarely (it rarely opens up with the game). What seems to be the problem? Any solutions?

**Comment by ron-popov** [comment] 2017-06-20 13:56
Please attach a screenshot of your GeoFS developer console window when the extension fails to load (Press F12 , click the console tab and screenshot your screen) to help us understand what is causing this issue.

**Comment by shantanubdas2002** [comment] 2017-06-20 14:14
![image](https://user-images.githubusercontent.com/29405098/27337720-51093bba-55e4-11e7-9d78-726ea5da9171.png)

This is what I get........

**Comment by ron-popov** [comment] 2017-06-20 14:36
This error happens due to SkyX aircraft warehouse plugin loading before GeoFS , this is fixed in the SkyX plugin manager , the beta version will be released in a couple of days.

**Comment by yotam180** [comment] 2017-06-20 14:38
The beta version will be released in a couple of days, so until it's released, this bug is critical.

Dear shantanubdas2002, I have spotted the origin of this problem, and working on fixing it.
Please be patient, it will be very appreciated.

Thanks,
Yotam.

**Comment by shantanubdas2002** [comment] 2017-06-20 14:54
So in the SkyX plugin manager it works? Which are you referring to? And why does skyx only work occasionally then?

and do we have to wait for the beta version to release before itll work?

**Comment by yotam180** [comment] 2017-06-20 15:03
I hope I can explain it clearly enough.
Firstly, the SkyX extension is what you're having problems with. In the future, we'll release something called SkyX plugin manager, which will let you manage your extensions. But currently, it's not yet available.

The problem is caused like that:
The extension is dynamically loaded. This means SkyX has to send a request to our servers, and the server sends it the extension code itself. This procedure takes time, usually between 0.5 and 3 seconds.
The SkyX script uses components from GeoFS' code (like the Aircraft object for instance). This means that before the extension code runs, GeoFS has to **create** the Aircraft object first.

If GeoFS is loaded, then SkyX server sends the code, then it's executed, well, it's alright.

But if SkyX's server sends the code before GeoFS has been loaded, a problem will occur, and the extension won't load correctly.

This problem is fixed in SkyX plugin manager (See: *future release*) because it works in a different way.

Until it's published, we'll do our best to fix the existing extension.

Sincerely,
Yotam.

**Comment by DemonzTimexs** [comment] 2017-06-22 10:37
@yotam180 
Hope my Screenshot also helps you.
![image](https://user-images.githubusercontent.com/29449907/27430090-db69d392-5764-11e7-83df-66625959c287.png)

**Comment by yotam180** [comment] 2017-06-22 17:13
SkyX plugin manager open beta has been opened, go download it at https://github.com/geofs-plugins/plugin-manager/releases

Well, this issue is no longer disturbing us, so I'm closing this thread down.

Thanks everyone.

**Closed as completed by yotam180** 2017-06-22 17:13 UTC
Labels: Bug

**Comment by kan78089** [comment] 2020-09-08 11:17
![image](https://user-images.githubusercontent.com/70948456/92469717-ec79b400-f1f2-11ea-9ada-40d2c6369c68.png)

its not working on chrome
